### ISSUE TITLE
'Grunt build' creates a package that misses ressources

### ISSUE THREAD

**Issue by dharma-guardian** [iamolivinius/octa#5]
The files in ```ui/assets``` are missing. Error: 
 ```Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://meajdbifgoamljaojeeglenlcemcfcgj/ui/assets/pattern-creator.css Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://meajdbifgoamljaojeeglenlcemcfcgj/ui/assets/vendor.js Failed to load resource: net::ERR_FILE_NOT_FOUND
chrome-extension://meajdbifgoamljaojeeglenlcemcfcgj/ui/assets/pattern-creator.js Failed to load resource: net::ERR_FILE_NOT_FOUND```
And the extension background script is missing files, too:
```Unchecked runtime.lastError while running tabs.executeScript: Failed to load file: "bower_components/jquery/dist/jquery.js". 
    at chrome-extension://meajdbifgoamljaojeeglenlcemcfcgj/scripts/background.js:1:257extensions::sendRequest:82 handleResponse
extensions::sendRequest:82 Unchecked runtime.lastError while running tabs.executeScript: Failed to load file: "scripts/contentscript.js". 
    at chrome-extension://meajdbifgoamljaojeeglenlcemcfcgj/scripts/background.js:1:358extensions::sendRequest:82 handleResponse```

**Comment by iamolivinius** [comment]
Fixed in ba1b2a729c6c70c1c3e8d3b4d1e3fcf2d1a85e1d
